import string
from pathlib import Path

class AUDIO_CONFIG:
    sampling_rate = 32000
    duration = 1
    hop_length = 251 # making it 128 in size
    fmin = 500
    fmax = 15000
    n_mels = 128
    n_fft = n_mels * 20
    samples = sampling_rate * duration
    padmode = 'reflect'
    
def fill_range(letter_start, letter_end, path_fill, dict_val={}):
    alphabet = list(string.ascii_lowercase)
    for a in alphabet[alphabet.index(letter_start):alphabet.index(letter_end)+1]:
        dict_val[a] = path_fill
    return dict_val

def get_dict_value(input_dir):
    dict_val = {}
    dict_val = fill_range('a','y',input_dir/"train_short_audio",dict_val)
    return dict_val

BIRD_CODE={'acafly': 0,
 'acowoo': 1,
 'aldfly': 2,
 'ameavo': 3,
 'amecro': 4,
 'amegfi': 5,
 'amekes': 6,
 'amepip': 7,
 'amered': 8,
 'amerob': 9,
 'amewig': 10,
 'amtspa': 11,
 'andsol1': 12,
 'annhum': 13,
 'astfly': 14,
 'azaspi1': 15,
 'babwar': 16,
 'baleag': 17,
 'balori': 18,
 'banana': 19,
 'banswa': 20,
 'banwre1': 21,
 'barant1': 22,
 'barswa': 23,
 'batpig1': 24,
 'bawswa1': 25,
 'bawwar': 26,
 'baywre1': 27,
 'bbwduc': 28,
 'bcnher': 29,
 'belkin1': 30,
 'belvir': 31,
 'bewwre': 32,
 'bkbmag1': 33,
 'bkbplo': 34,
 'bkbwar': 35,
 'bkcchi': 36,
 'bkhgro': 37,
 'bkmtou1': 38,
 'bknsti': 39,
 'blbgra1': 40,
 'blbthr1': 41,
 'blcjay1': 42,
 'blctan1': 43,
 'blhpar1': 44,
 'blkpho': 45,
 'blsspa1': 46,
 'blugrb1': 47,
 'blujay': 48,
 'bncfly': 49,
 'bnhcow': 50,
 'bobfly1': 51,
 'bongul': 52,
 'botgra': 53,
 'brbmot1': 54,
 'brbsol1': 55,
 'brcvir1': 56,
 'brebla': 57,
 'brncre': 58,
 'brnjay': 59,
 'brnthr': 60,
 'brratt1': 61,
 'brwhaw': 62,
 'brwpar1': 63,
 'btbwar': 64,
 'btnwar': 65,
 'btywar': 66,
 'bucmot2': 67,
 'buggna': 68,
 'bugtan': 69,
 'buhvir': 70,
 'bulori': 71,
 'burwar1': 72,
 'bushti': 73,
 'butsal1': 74,
 'buwtea': 75,
 'cacgoo1': 76,
 'cacwre': 77,
 'calqua': 78,
 'caltow': 79,
 'cangoo': 80,
 'canwar': 81,
 'carchi': 82,
 'carwre': 83,
 'casfin': 84,
 'caskin': 85,
 'caster1': 86,
 'casvir': 87,
 'categr': 88,
 'ccbfin': 89,
 'cedwax': 90,
 'chbant1': 91,
 'chbchi': 92,
 'chbwre1': 93,
 'chcant2': 94,
 'chispa': 95,
 'chswar': 96,
 'cinfly2': 97,
 'clanut': 98,
 'clcrob': 99,
 'cliswa': 100,
 'cobtan1': 101,
 'cocwoo1': 102,
 'cogdov': 103,
 'colcha1': 104,
 'coltro1': 105,
 'comgol': 106,
 'comgra': 107,
 'comloo': 108,
 'commer': 109,
 'compau': 110,
 'compot1': 111,
 'comrav': 112,
 'comyel': 113,
 'coohaw': 114,
 'cotfly1': 115,
 'cowscj1': 116,
 'cregua1': 117,
 'creoro1': 118,
 'crfpar': 119,
 'cubthr': 120,
 'daejun': 121,
 'dowwoo': 122,
 'ducfly': 123,
 'dusfly': 124,
 'easblu': 125,
 'easkin': 126,
 'easmea': 127,
 'easpho': 128,
 'eastow': 129,
 'eawpew': 130,
 'eletro': 131,
 'eucdov': 132,
 'eursta': 133,
 'fepowl': 134,
 'fiespa': 135,
 'flrtan1': 136,
 'foxspa': 137,
 'gadwal': 138,
 'gamqua': 139,
 'gartro1': 140,
 'gbbgul': 141,
 'gbwwre1': 142,
 'gcrwar': 143,
 'gilwoo': 144,
 'gnttow': 145,
 'gnwtea': 146,
 'gocfly1': 147,
 'gockin': 148,
 'gocspa': 149,
 'goftyr1': 150,
 'gohque1': 151,
 'goowoo1': 152,
 'grasal1': 153,
 'grbani': 154,
 'grbher3': 155,
 'grcfly': 156,
 'greegr': 157,
 'grekis': 158,
 'grepew': 159,
 'grethr1': 160,
 'gretin1': 161,
 'greyel': 162,
 'grhcha1': 163,
 'grhowl': 164,
 'grnher': 165,
 'grnjay': 166,
 'grtgra': 167,
 'grycat': 168,
 'gryhaw2': 169,
 'gwfgoo': 170,
 'haiwoo': 171,
 'heptan': 172,
 'hergul': 173,
 'herthr': 174,
 'herwar': 175,
 'higmot1': 176,
 'hofwoo1': 177,
 'houfin': 178,
 'houspa': 179,
 'houwre': 180,
 'hutvir': 181,
 'incdov': 182,
 'indbun': 183,
 'kebtou1': 184,
 'killde': 185,
 'labwoo': 186,
 'larspa': 187,
 'laufal1': 188,
 'laugul': 189,
 'lazbun': 190,
 'leafly': 191,
 'leasan': 192,
 'lesgol': 193,
 'lesgre1': 194,
 'lesvio1': 195,
 'linspa': 196,
 'linwoo1': 197,
 'littin1': 198,
 'lobdow': 199,
 'lobgna5': 200,
 'logshr': 201,
 'lotduc': 202,
 'lotman1': 203,
 'lucwar': 204,
 'macwar': 205,
 'magwar': 206,
 'mallar3': 207,
 'marwre': 208,
 'mastro1': 209,
 'meapar': 210,
 'melbla1': 211,
 'monoro1': 212,
 'mouchi': 213,
 'moudov': 214,
 'mouela1': 215,
 'mouqua': 216,
 'mouwar': 217,
 'mutswa': 218,
 'naswar': 219,
 'norcar': 220,
 'norfli': 221,
 'normoc': 222,
 'norpar': 223,
 'norsho': 224,
 'norwat': 225,
 'nrwswa': 226,
 'nutwoo': 227,
 'oaktit': 228,
 'obnthr1': 229,
 'ocbfly1': 230,
 'oliwoo1': 231,
 'olsfly': 232,
 'orbeup1': 233,
 'orbspa1': 234,
 'orcpar': 235,
 'orcwar': 236,
 'orfpar': 237,
 'osprey': 238,
 'ovenbi1': 239,
 'pabspi1': 240,
 'paltan1': 241,
 'palwar': 242,
 'pasfly': 243,
 'pavpig2': 244,
 'phivir': 245,
 'pibgre': 246,
 'pilwoo': 247,
 'pinsis': 248,
 'pirfly1': 249,
 'plawre1': 250,
 'plaxen1': 251,
 'plsvir': 252,
 'plupig2': 253,
 'prowar': 254,
 'purfin': 255,
 'purgal2': 256,
 'putfru1': 257,
 'pygnut': 258,
 'rawwre1': 259,
 'rcatan1': 260,
 'rebnut': 261,
 'rebsap': 262,
 'rebwoo': 263,
 'redcro': 264,
 'reevir1': 265,
 'rehbar1': 266,
 'relpar': 267,
 'reshaw': 268,
 'rethaw': 269,
 'rewbla': 270,
 'ribgul': 271,
 'rinkin1': 272,
 'roahaw': 273,
 'robgro': 274,
 'rocpig': 275,
 'rotbec': 276,
 'royter1': 277,
 'rthhum': 278,
 'rtlhum': 279,
 'ruboro1': 280,
 'rubpep1': 281,
 'rubrob': 282,
 'rubwre1': 283,
 'ruckin': 284,
 'rucspa1': 285,
 'rucwar': 286,
 'rucwar1': 287,
 'rudpig': 288,
 'rudtur': 289,
 'rufhum': 290,
 'rugdov': 291,
 'rumfly1': 292,
 'runwre1': 293,
 'rutjac1': 294,
 'saffin': 295,
 'sancra': 296,
 'sander': 297,
 'savspa': 298,
 'saypho': 299,
 'scamac1': 300,
 'scatan': 301,
 'scbwre1': 302,
 'scptyr1': 303,
 'scrtan1': 304,
 'semplo': 305,
 'shicow': 306,
 'sibtan2': 307,
 'sinwre1': 308,
 'sltred': 309,
 'smbani': 310,
 'snogoo': 311,
 'sobtyr1': 312,
 'socfly1': 313,
 'solsan': 314,
 'sonspa': 315,
 'soulap1': 316,
 'sposan': 317,
 'spotow': 318,
 'spvear1': 319,
 'squcuc1': 320,
 'stbori': 321,
 'stejay': 322,
 'sthant1': 323,
 'sthwoo1': 324,
 'strcuc1': 325,
 'strfly1': 326,
 'strsal1': 327,
 'stvhum2': 328,
 'subfly': 329,
 'sumtan': 330,
 'swaspa': 331,
 'swathr': 332,
 'tenwar': 333,
 'thbeup1': 334,
 'thbkin': 335,
 'thswar1': 336,
 'towsol': 337,
 'treswa': 338,
 'trogna1': 339,
 'trokin': 340,
 'tromoc': 341,
 'tropar': 342,
 'tropew1': 343,
 'tuftit': 344,
 'tunswa': 345,
 'veery': 346,
 'verdin': 347,
 'vigswa': 348,
 'warvir': 349,
 'wbwwre1': 350,
 'webwoo1': 351,
 'wegspa1': 352,
 'wesant1': 353,
 'wesblu': 354,
 'weskin': 355,
 'wesmea': 356,
 'westan': 357,
 'wewpew': 358,
 'whbman1': 359,
 'whbnut': 360,
 'whcpar': 361,
 'whcsee1': 362,
 'whcspa': 363,
 'whevir': 364,
 'whfpar1': 365,
 'whimbr': 366,
 'whiwre1': 367,
 'whtdov': 368,
 'whtspa': 369,
 'whwbec1': 370,
 'whwdov': 371,
 'wilfly': 372,
 'willet1': 373,
 'wilsni1': 374,
 'wiltur': 375,
 'wlswar': 376,
 'wooduc': 377,
 'woothr': 378,
 'wrenti': 379,
 'y00475': 380,
 'yebcha': 381,
 'yebela1': 382,
 'yebfly': 383,
 'yebori1': 384,
 'yebsap': 385,
 'yebsee1': 386,
 'yefgra1': 387,
 'yegvir': 388,
 'yehbla': 389,
 'yehcar1': 390,
 'yelgro': 391,
 'yelwar': 392,
 'yeofly1': 393,
 'yerwar': 394,
 'yeteup1': 395,
 'yetvir': 396}

EBIRD_LABEL = {'aldfly': 'Empidonax alnorum_Alder Flycatcher',
 'ameavo': 'Recurvirostra americana_American Avocet',
 'amebit': 'Botaurus lentiginosus_American Bittern',
 'amecro': 'Corvus brachyrhynchos_American Crow',
 'amegfi': 'Spinus tristis_American Goldfinch',
 'amekes': 'Falco sparverius_American Kestrel',
 'amepip': 'Anthus rubescens_American Pipit',
 'amered': 'Setophaga ruticilla_American Redstart',
 'amerob': 'Turdus migratorius_American Robin',
 'amewig': 'Mareca americana_American Wigeon',
 'amewoo': 'Scolopax minor_American Woodcock',
 'amtspa': 'Spizelloides arborea_American Tree Sparrow',
 'annhum': "Calypte anna_Anna's Hummingbird",
 'astfly': 'Myiarchus cinerascens_Ash-throated Flycatcher',
 'baisan': "Calidris bairdii_Baird's Sandpiper",
 'baleag': 'Haliaeetus leucocephalus_Bald Eagle',
 'balori': 'Icterus galbula_Baltimore Oriole',
 'banswa': 'Riparia riparia_Bank Swallow',
 'barswa': 'Hirundo rustica_Barn Swallow',
 'bawwar': 'Mniotilta varia_Black-and-white Warbler',
 'belkin1': 'Megaceryle alcyon_Belted Kingfisher',
 'belspa2': "Artemisiospiza belli_Bell's Sparrow",
 'bewwre': "Thryomanes bewickii_Bewick's Wren",
 'bkbcuc': 'Coccyzus erythropthalmus_Black-billed Cuckoo',
 'bkbmag1': 'Pica hudsonia_Black-billed Magpie',
 'bkbwar': 'Setophaga fusca_Blackburnian Warbler',
 'bkcchi': 'Poecile atricapillus_Black-capped Chickadee',
 'bkchum': 'Archilochus alexandri_Black-chinned Hummingbird',
 'bkhgro': 'Pheucticus melanocephalus_Black-headed Grosbeak',
 'bkpwar': 'Setophaga striata_Blackpoll Warbler',
 'bktspa': 'Amphispiza bilineata_Black-throated Sparrow',
 'blkpho': 'Sayornis nigricans_Black Phoebe',
 'blugrb1': 'Passerina caerulea_Blue Grosbeak',
 'blujay': 'Cyanocitta cristata_Blue Jay',
 'bnhcow': 'Molothrus ater_Brown-headed Cowbird',
 'boboli': 'Dolichonyx oryzivorus_Bobolink',
 'bongul': "Chroicocephalus philadelphia_Bonaparte's Gull",
 'brdowl': 'Strix varia_Barred Owl',
 'brebla': "Euphagus cyanocephalus_Brewer's Blackbird",
 'brespa': "Spizella breweri_Brewer's Sparrow",
 'brncre': 'Certhia americana_Brown Creeper',
 'brnthr': 'Toxostoma rufum_Brown Thrasher',
 'brthum': 'Selasphorus platycercus_Broad-tailed Hummingbird',
 'brwhaw': 'Buteo platypterus_Broad-winged Hawk',
 'btbwar': 'Setophaga caerulescens_Black-throated Blue Warbler',
 'btnwar': 'Setophaga virens_Black-throated Green Warbler',
 'btywar': 'Setophaga nigrescens_Black-throated Gray Warbler',
 'buffle': 'Bucephala albeola_Bufflehead',
 'buggna': 'Polioptila caerulea_Blue-gray Gnatcatcher',
 'buhvir': 'Vireo solitarius_Blue-headed Vireo',
 'bulori': "Icterus bullockii_Bullock's Oriole",
 'bushti': 'Psaltriparus minimus_Bushtit',
 'buwtea': 'Spatula discors_Blue-winged Teal',
 'buwwar': 'Vermivora cyanoptera_Blue-winged Warbler',
 'cacwre': 'Campylorhynchus brunneicapillus_Cactus Wren',
 'calgul': 'Larus californicus_California Gull',
 'calqua': 'Callipepla californica_California Quail',
 'camwar': 'Setophaga tigrina_Cape May Warbler',
 'cangoo': 'Branta canadensis_Canada Goose',
 'canwar': 'Cardellina canadensis_Canada Warbler',
 'canwre': 'Catherpes mexicanus_Canyon Wren',
 'carwre': 'Thryothorus ludovicianus_Carolina Wren',
 'casfin': "Haemorhous cassinii_Cassin's Finch",
 'caster1': 'Hydroprogne caspia_Caspian Tern',
 'casvir': "Vireo cassinii_Cassin's Vireo",
 'cedwax': 'Bombycilla cedrorum_Cedar Waxwing',
 'chispa': 'Spizella passerina_Chipping Sparrow',
 'chiswi': 'Chaetura pelagica_Chimney Swift',
 'chswar': 'Setophaga pensylvanica_Chestnut-sided Warbler',
 'chukar': 'Alectoris chukar_Chukar',
 'clanut': "Nucifraga columbiana_Clark's Nutcracker",
 'cliswa': 'Petrochelidon pyrrhonota_Cliff Swallow',
 'comgol': 'Bucephala clangula_Common Goldeneye',
 'comgra': 'Quiscalus quiscula_Common Grackle',
 'comloo': 'Gavia immer_Common Loon',
 'commer': 'Mergus merganser_Common Merganser',
 'comnig': 'Chordeiles minor_Common Nighthawk',
 'comrav': 'Corvus corax_Common Raven',
 'comred': 'Acanthis flammea_Common Redpoll',
 'comter': 'Sterna hirundo_Common Tern',
 'comyel': 'Geothlypis trichas_Common Yellowthroat',
 'coohaw': "Accipiter cooperii_Cooper's Hawk",
 'coshum': "Calypte costae_Costa's Hummingbird",
 'cowscj1': 'Aphelocoma californica_California Scrub-Jay',
 'daejun': 'Junco hyemalis_Dark-eyed Junco',
 'doccor': 'Phalacrocorax auritus_Double-crested Cormorant',
 'dowwoo': 'Dryobates pubescens_Downy Woodpecker',
 'dusfly': 'Empidonax oberholseri_Dusky Flycatcher',
 'eargre': 'Podiceps nigricollis_Eared Grebe',
 'easblu': 'Sialia sialis_Eastern Bluebird',
 'easkin': 'Tyrannus tyrannus_Eastern Kingbird',
 'easmea': 'Sturnella magna_Eastern Meadowlark',
 'easpho': 'Sayornis phoebe_Eastern Phoebe',
 'eastow': 'Pipilo erythrophthalmus_Eastern Towhee',
 'eawpew': 'Contopus virens_Eastern Wood-Pewee',
 'eucdov': 'Streptopelia decaocto_Eurasian Collared-Dove',
 'eursta': 'Sturnus vulgaris_European Starling',
 'evegro': 'Coccothraustes vespertinus_Evening Grosbeak',
 'fiespa': 'Spizella pusilla_Field Sparrow',
 'fiscro': 'Corvus ossifragus_Fish Crow',
 'foxspa': 'Passerella iliaca_Fox Sparrow',
 'gadwal': 'Mareca strepera_Gadwall',
 'gcrfin': 'Leucosticte tephrocotis_Gray-crowned Rosy-Finch',
 'gnttow': 'Pipilo chlorurus_Green-tailed Towhee',
 'gnwtea': 'Anas crecca_Green-winged Teal',
 'gockin': 'Regulus satrapa_Golden-crowned Kinglet',
 'gocspa': 'Zonotrichia atricapilla_Golden-crowned Sparrow',
 'goleag': 'Aquila chrysaetos_Golden Eagle',
 'grbher3': 'Ardea herodias_Great Blue Heron',
 'grcfly': 'Myiarchus crinitus_Great Crested Flycatcher',
 'greegr': 'Ardea alba_Great Egret',
 'greroa': 'Geococcyx californianus_Greater Roadrunner',
 'greyel': 'Tringa melanoleuca_Greater Yellowlegs',
 'grhowl': 'Bubo virginianus_Great Horned Owl',
 'grnher': 'Butorides virescens_Green Heron',
 'grtgra': 'Quiscalus mexicanus_Great-tailed Grackle',
 'grycat': 'Dumetella carolinensis_Gray Catbird',
 'gryfly': 'Empidonax wrightii_Gray Flycatcher',
 'haiwoo': 'Dryobates villosus_Hairy Woodpecker',
 'hamfly': "Empidonax hammondii_Hammond's Flycatcher",
 'hergul': 'Larus argentatus_Herring Gull',
 'herthr': 'Catharus guttatus_Hermit Thrush',
 'hoomer': 'Lophodytes cucullatus_Hooded Merganser',
 'hoowar': 'Setophaga citrina_Hooded Warbler',
 'horgre': 'Podiceps auritus_Horned Grebe',
 'horlar': 'Eremophila alpestris_Horned Lark',
 'houfin': 'Haemorhous mexicanus_House Finch',
 'houspa': 'Passer domesticus_House Sparrow',
 'houwre': 'Troglodytes aedon_House Wren',
 'indbun': 'Passerina cyanea_Indigo Bunting',
 'juntit1': 'Baeolophus ridgwayi_Juniper Titmouse',
 'killde': 'Charadrius vociferus_Killdeer',
 'labwoo': 'Dryobates scalaris_Ladder-backed Woodpecker',
 'larspa': 'Chondestes grammacus_Lark Sparrow',
 'lazbun': 'Passerina amoena_Lazuli Bunting',
 'leabit': 'Ixobrychus exilis_Least Bittern',
 'leafly': 'Empidonax minimus_Least Flycatcher',
 'leasan': 'Calidris minutilla_Least Sandpiper',
 'lecthr': "Toxostoma lecontei_LeConte's Thrasher",
 'lesgol': 'Spinus psaltria_Lesser Goldfinch',
 'lesnig': 'Chordeiles acutipennis_Lesser Nighthawk',
 'lesyel': 'Tringa flavipes_Lesser Yellowlegs',
 'lewwoo': "Melanerpes lewis_Lewis's Woodpecker",
 'linspa': "Melospiza lincolnii_Lincoln's Sparrow",
 'lobcur': 'Numenius americanus_Long-billed Curlew',
 'lobdow': 'Limnodromus scolopaceus_Long-billed Dowitcher',
 'logshr': 'Lanius ludovicianus_Loggerhead Shrike',
 'lotduc': 'Clangula hyemalis_Long-tailed Duck',
 'louwat': 'Parkesia motacilla_Louisiana Waterthrush',
 'macwar': "Geothlypis tolmiei_MacGillivray's Warbler",
 'magwar': 'Setophaga magnolia_Magnolia Warbler',
 'mallar3': 'Anas platyrhynchos_Mallard',
 'marwre': 'Cistothorus palustris_Marsh Wren',
 'merlin': 'Falco columbarius_Merlin',
 'moublu': 'Sialia currucoides_Mountain Bluebird',
 'mouchi': 'Poecile gambeli_Mountain Chickadee',
 'moudov': 'Zenaida macroura_Mourning Dove',
 'norcar': 'Cardinalis cardinalis_Northern Cardinal',
 'norfli': 'Colaptes auratus_Northern Flicker',
 'norhar2': 'Circus hudsonius_Northern Harrier',
 'normoc': 'Mimus polyglottos_Northern Mockingbird',
 'norpar': 'Setophaga americana_Northern Parula',
 'norpin': 'Anas acuta_Northern Pintail',
 'norsho': 'Spatula clypeata_Northern Shoveler',
 'norwat': 'Parkesia noveboracensis_Northern Waterthrush',
 'nrwswa': 'Stelgidopteryx serripennis_Northern Rough-winged Swallow',
 'nutwoo': "Dryobates nuttallii_Nuttall's Woodpecker",
 'olsfly': 'Contopus cooperi_Olive-sided Flycatcher',
 'orcwar': 'Leiothlypis celata_Orange-crowned Warbler',
 'osprey': 'Pandion haliaetus_Osprey',
 'ovenbi1': 'Seiurus aurocapilla_Ovenbird',
 'palwar': 'Setophaga palmarum_Palm Warbler',
 'pasfly': 'Empidonax difficilis_Pacific-slope Flycatcher',
 'pecsan': 'Calidris melanotos_Pectoral Sandpiper',
 'perfal': 'Falco peregrinus_Peregrine Falcon',
 'phaino': 'Phainopepla nitens_Phainopepla',
 'pibgre': 'Podilymbus podiceps_Pied-billed Grebe',
 'pilwoo': 'Dryocopus pileatus_Pileated Woodpecker',
 'pingro': 'Pinicola enucleator_Pine Grosbeak',
 'pinjay': 'Gymnorhinus cyanocephalus_Pinyon Jay',
 'pinsis': 'Spinus pinus_Pine Siskin',
 'pinwar': 'Setophaga pinus_Pine Warbler',
 'plsvir': 'Vireo plumbeus_Plumbeous Vireo',
 'prawar': 'Setophaga discolor_Prairie Warbler',
 'purfin': 'Haemorhous purpureus_Purple Finch',
 'pygnut': 'Sitta pygmaea_Pygmy Nuthatch',
 'rebmer': 'Mergus serrator_Red-breasted Merganser',
 'rebnut': 'Sitta canadensis_Red-breasted Nuthatch',
 'rebsap': 'Sphyrapicus ruber_Red-breasted Sapsucker',
 'rebwoo': 'Melanerpes carolinus_Red-bellied Woodpecker',
 'redcro': 'Loxia curvirostra_Red Crossbill',
 'redhea': 'Aythya americana_Redhead',
 'reevir1': 'Vireo olivaceus_Red-eyed Vireo',
 'renpha': 'Phalaropus lobatus_Red-necked Phalarope',
 'reshaw': 'Buteo lineatus_Red-shouldered Hawk',
 'rethaw': 'Buteo jamaicensis_Red-tailed Hawk',
 'rewbla': 'Agelaius phoeniceus_Red-winged Blackbird',
 'ribgul': 'Larus delawarensis_Ring-billed Gull',
 'rinduc': 'Aythya collaris_Ring-necked Duck',
 'robgro': 'Pheucticus ludovicianus_Rose-breasted Grosbeak',
 'rocpig': 'Columba livia_Rock Pigeon',
 'rocwre': 'Salpinctes obsoletus_Rock Wren',
 'rthhum': 'Archilochus colubris_Ruby-throated Hummingbird',
 'ruckin': 'Regulus calendula_Ruby-crowned Kinglet',
 'rudduc': 'Oxyura jamaicensis_Ruddy Duck',
 'rufgro': 'Bonasa umbellus_Ruffed Grouse',
 'rufhum': 'Selasphorus rufus_Rufous Hummingbird',
 'rusbla': 'Euphagus carolinus_Rusty Blackbird',
 'sagspa1': 'Artemisiospiza nevadensis_Sagebrush Sparrow',
 'sagthr': 'Oreoscoptes montanus_Sage Thrasher',
 'savspa': 'Passerculus sandwichensis_Savannah Sparrow',
 'saypho': "Sayornis saya_Say's Phoebe",
 'scatan': 'Piranga olivacea_Scarlet Tanager',
 'scoori': "Icterus parisorum_Scott's Oriole",
 'semplo': 'Charadrius semipalmatus_Semipalmated Plover',
 'semsan': 'Calidris pusilla_Semipalmated Sandpiper',
 'sheowl': 'Asio flammeus_Short-eared Owl',
 'shshaw': 'Accipiter striatus_Sharp-shinned Hawk',
 'snobun': 'Plectrophenax nivalis_Snow Bunting',
 'snogoo': 'Anser caerulescens_Snow Goose',
 'solsan': 'Tringa solitaria_Solitary Sandpiper',
 'sonspa': 'Melospiza melodia_Song Sparrow',
 'sora': 'Porzana carolina_Sora',
 'sposan': 'Actitis macularius_Spotted Sandpiper',
 'spotow': 'Pipilo maculatus_Spotted Towhee',
 'stejay': "Cyanocitta stelleri_Steller's Jay",
 'swahaw': "Buteo swainsoni_Swainson's Hawk",
 'swaspa': 'Melospiza georgiana_Swamp Sparrow',
 'swathr': "Catharus ustulatus_Swainson's Thrush",
 'treswa': 'Tachycineta bicolor_Tree Swallow',
 'truswa': 'Cygnus buccinator_Trumpeter Swan',
 'tuftit': 'Baeolophus bicolor_Tufted Titmouse',
 'tunswa': 'Cygnus columbianus_Tundra Swan',
 'veery': 'Catharus fuscescens_Veery',
 'vesspa': 'Pooecetes gramineus_Vesper Sparrow',
 'vigswa': 'Tachycineta thalassina_Violet-green Swallow',
 'warvir': 'Vireo gilvus_Warbling Vireo',
 'wesblu': 'Sialia mexicana_Western Bluebird',
 'wesgre': 'Aechmophorus occidentalis_Western Grebe',
 'weskin': 'Tyrannus verticalis_Western Kingbird',
 'wesmea': 'Sturnella neglecta_Western Meadowlark',
 'wessan': 'Calidris mauri_Western Sandpiper',
 'westan': 'Piranga ludoviciana_Western Tanager',
 'wewpew': 'Contopus sordidulus_Western Wood-Pewee',
 'whbnut': 'Sitta carolinensis_White-breasted Nuthatch',
 'whcspa': 'Zonotrichia leucophrys_White-crowned Sparrow',
 'whfibi': 'Plegadis chihi_White-faced Ibis',
 'whtspa': 'Zonotrichia albicollis_White-throated Sparrow',
 'whtswi': 'Aeronautes saxatalis_White-throated Swift',
 'wilfly': 'Empidonax traillii_Willow Flycatcher',
 'wilsni1': "Gallinago delicata_Wilson's Snipe",
 'wiltur': 'Meleagris gallopavo_Wild Turkey',
 'winwre3': 'Troglodytes hiemalis_Winter Wren',
 'wlswar': "Cardellina pusilla_Wilson's Warbler",
 'wooduc': 'Aix sponsa_Wood Duck',
 'wooscj2': "Aphelocoma woodhouseii_Woodhouse's Scrub-Jay",
 'woothr': 'Hylocichla mustelina_Wood Thrush',
 'y00475': 'Fulica americana_American Coot',
 'yebfly': 'Empidonax flaviventris_Yellow-bellied Flycatcher',
 'yebsap': 'Sphyrapicus varius_Yellow-bellied Sakpsucker',
 'yehbla': 'Xanthocephalus xanthocephalus_Yellow-headed Blackbird',
 'yelwar': 'Setophaga petechia_Yellow Warbler',
 'yerwar': 'Setophaga coronata_Yellow-rumped Warbler',
 'yetvir': 'Vireo flavifrons_Yellow-throated Vireo'}

INV_EBIRD_LABEL = {v: k for k, v in EBIRD_LABEL.items()}
